# 1. Jupyter NoteBook 시작

In [1]:
print("Hello")

Hello


In [2]:
"안녕하세요"

'안녕하세요'

In [4]:
import pandas as pd

In [6]:
pd.__version__

'0.24.2'

In [7]:
"SK하이닉스"

'SK하이닉스'

In [8]:
a = {'name':['Jane','Tom','Alice','John'],
     'age':[34,27,51,45],
     'point':[80,70,90,60]}
df1 = pd.DataFrame(a,columns=['name','point','age','etc'],
                   index=['학생1','학생2','학생3','학생4'])

In [9]:
df1

name  point  age  etc
학생1   Jane     80   34  NaN
학생2    Tom     70   27  NaN
학생3  Alice     90   51  NaN
학생4   John     60   45  NaN

In [14]:
df1.loc['학생1':'학생2']

name  point  age  etc
학생1  Jane     80   34  NaN
학생2   Tom     70   27  NaN

In [16]:
df1.loc['학생1':'학생2','name':'age']

name  point  age
학생1  Jane     80   34
학생2   Tom     70   27

In [18]:
df1.iloc[0:1]

name  point  age  etc
학생1  Jane     80   34  NaN

In [19]:
df1.iloc[0:1,0:2]

name  point
학생1  Jane     80

In [20]:
df1

name  point  age  etc
학생1   Jane     80   34  NaN
학생2    Tom     70   27  NaN
학생3  Alice     90   51  NaN
학생4   John     60   45  NaN

In [24]:
df1.loc['학생1','etc'] = 1

In [29]:
df1.loc[:,'etc'] = 2

In [30]:
df1

name  point  age  etc
학생1   Jane     80   34    2
학생2    Tom     70   27    2
학생3  Alice     90   51    2
학생4   John     60   45    2

In [34]:
df1.loc['학생5',:] = ['Sophia', 100, 9,3];
df1.loc['학생6',:] = ['James', 77, 21, 4]

In [35]:
df1

name  point   age  etc
학생1    Jane   80.0  34.0  2.0
학생2     Tom   70.0  27.0  2.0
학생3   Alice   90.0  51.0  2.0
학생4    John   60.0  45.0  2.0
학생5  Sophia  100.0   9.0  3.0
학생6   James   77.0  21.0  4.0

In [38]:
df1['point']>=75

학생1     True
학생2    False
학생3     True
학생4    False
학생5     True
학생6     True
Name: point, dtype: bool

In [39]:
df1[df1['point']>=75]

name  point   age  etc
학생1    Jane   80.0  34.0  2.0
학생3   Alice   90.0  51.0  2.0
학생5  Sophia  100.0   9.0  3.0
학생6   James   77.0  21.0  4.0

In [45]:
df1[df1['point']>=75]

name  point   age  etc
학생1    Jane   80.0  34.0  2.0
학생3   Alice   90.0  51.0  2.0
학생5  Sophia  100.0   9.0  3.0
학생6   James   77.0  21.0  4.0

In [46]:
import numpy as np

In [47]:
n1 = np.arange(1,21)

In [48]:
n1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [49]:
n1>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [50]:
n1[n1>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [51]:
df1

name  point   age  etc
학생1    Jane   80.0  34.0  2.0
학생2     Tom   70.0  27.0  2.0
학생3   Alice   90.0  51.0  2.0
학생4    John   60.0  45.0  2.0
학생5  Sophia  100.0   9.0  3.0
학생6   James   77.0  21.0  4.0

In [53]:
df1[df1['age']>=30]

name  point   age  etc
학생1   Jane   80.0  34.0  2.0
학생3  Alice   90.0  51.0  2.0
학생4   John   60.0  45.0  2.0

In [55]:
df1.loc[df1['age']>=30,:]

name  point   age  etc
학생1   Jane   80.0  34.0  2.0
학생3  Alice   90.0  51.0  2.0
학생4   John   60.0  45.0  2.0

In [56]:
df1

name  point   age  etc
학생1    Jane   80.0  34.0  2.0
학생2     Tom   70.0  27.0  2.0
학생3   Alice   90.0  51.0  2.0
학생4    John   60.0  45.0  2.0
학생5  Sophia  100.0   9.0  3.0
학생6   James   77.0  21.0  4.0

In [57]:
df1[(df1['point']>75)&(df1['age']>=30)]

name  point   age  etc
학생1   Jane   80.0  34.0  2.0
학생3  Alice   90.0  51.0  2.0

In [59]:
df1.loc[(df1['point']>75)&(df1['age']>=30),:]

name  point   age  etc
학생1   Jane   80.0  34.0  2.0
학생3  Alice   90.0  51.0  2.0

In [72]:
df1[(df1['point']>75)&(df1['age']>=30)][['name','age']]

name   age
학생1   Jane  34.0
학생3  Alice  51.0

In [75]:
df1.loc[df1['age']>=30,['name','age']]

name   age
학생1   Jane  34.0
학생3  Alice  51.0
학생4   John  45.0

In [80]:
df1.loc[df1['age']>=30,'name':'age']

name  point   age
학생1   Jane   80.0  34.0
학생3  Alice   90.0  51.0
학생4   John   60.0  45.0

In [93]:
df1.loc[df1['point']<=70,'etc'] = 5

In [97]:
df1

name  point   age  etc
학생1    Jane   80.0  34.0  2.0
학생2     Tom   70.0  27.0  5.0
학생3   Alice   90.0  51.0  2.0
학생4    John   60.0  45.0  5.0
학생5  Sophia  100.0   9.0  3.0
학생6   James   77.0  21.0  4.0

In [98]:
df1['point'].mean()

79.5

In [99]:
df1['point'].sum()

477.0

In [100]:
df1['point'].var()

201.5

In [101]:
df1['point'].std()

14.19506956657839

In [102]:
df1.describe()

point        age       etc
count    6.00000   6.000000  6.000000
mean    79.50000  31.166667  3.500000
std     14.19507  15.523101  1.378405
min     60.00000   9.000000  2.000000
25%     71.75000  22.500000  2.250000
50%     78.50000  30.500000  3.500000
75%     87.50000  42.250000  4.750000
max    100.00000  51.000000  5.000000

In [103]:
df1

name  point   age  etc
학생1    Jane   80.0  34.0  2.0
학생2     Tom   70.0  27.0  5.0
학생3   Alice   90.0  51.0  2.0
학생4    John   60.0  45.0  5.0
학생5  Sophia  100.0   9.0  3.0
학생6   James   77.0  21.0  4.0

In [104]:
df1.drop('학생1')

name  point   age  etc
학생2     Tom   70.0  27.0  5.0
학생3   Alice   90.0  51.0  2.0
학생4    John   60.0  45.0  5.0
학생5  Sophia  100.0   9.0  3.0
학생6   James   77.0  21.0  4.0